# Generated by Django 4.0.3 on 2024-02-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='last_name',
        ),
    ]
