# Generated by Django 4.0.3 on 2024-02-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_technician_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='technician',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
